#!/bin/bash
#bashtest init

arg=$1

# Helper funcs
function changedir {
	cd "$1"
}

function runtestfile {
	# read -r ans
	case $arg in
	cli-2-1 ) chmod +x "${BASHDIR}/bashtests/${arg}.sh"
		"${BASHDIR}/bashtests/$arg.sh"
		;;
	cli-2-2 ) chmod +x "${BASHDIR}/bashtests/${arg}.sh"
		"${BASHDIR}/bashtests/$arg.sh"
		;;
	cli-2-3 ) chmod +x "${BASHDIR}/bashtests/${arg}.sh"
		"${BASHDIR}/bashtests/$arg.sh"
		;;
	*) echo "The $arg argument can't be recognized. Try again."
	   ;;
	esac
}


if [[ -z "$arg" ]]; then
	echo "The 'bashtest' command needs an argument in order to be executed.";
else
	runtestfile
fi